//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.Companions = new HashSet<Companion>();
            this.Recipes = new HashSet<Recipe>();
            this.Tradeskills = new HashSet<Tradeskill>();
        }
    
        public int CharacterId { get; set; }
        public long LastModified { get; set; }
        public string Name { get; set; }
        public int RealmId { get; set; }
        public int RaceId { get; set; }
        public int ClassId { get; set; }
        public int Gender { get; set; }
        public int Level { get; set; }
        public int AchievementPoints { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Race Race { get; set; }
        public virtual Realm Realm { get; set; }
        public virtual ICollection<Companion> Companions { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
        public virtual ICollection<Tradeskill> Tradeskills { get; set; }
    }
}
