//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public int ClassId { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public byte R { get; set; }
        public byte G { get; set; }
        public byte B { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
    }
}
