//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companion
    {
        public Companion()
        {
            this.Items = new HashSet<Item>();
            this.Characters = new HashSet<Character>();
        }
    
        public int CompanionId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
