//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Auctions = new HashSet<Auction>();
            this.Reagents = new HashSet<Reagent>();
            this.Recipes = new HashSet<Recipe>();
            this.Recipes1 = new HashSet<Recipe>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string JSON { get; set; }
        public string JSON_zhTW { get; set; }
        public Nullable<int> CompanionId { get; set; }
        public Nullable<long> ServerwideAverage { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> BindOnPickup { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string SourceType { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual Companion Companion { get; set; }
        public virtual ICollection<Reagent> Reagents { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
        public virtual ICollection<Recipe> Recipes1 { get; set; }
    }
}
