//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realm
    {
        public Realm()
        {
            this.Auctions = new HashSet<Auction>();
            this.Characters = new HashSet<Character>();
        }
    
        public int RealmId { get; set; }
        public string Type { get; set; }
        public string Population { get; set; }
        public bool Queue { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Battlegroup { get; set; }
    
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
