//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Reagents = new HashSet<Reagent>();
            this.Characters = new HashSet<Character>();
        }
    
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> RecipeItemId { get; set; }
        public Nullable<int> CraftedItemId { get; set; }
        public int TradeskillId { get; set; }
        public string Source { get; set; }
        public Nullable<long> ServerwideAverage { get; set; }
        public Nullable<long> CurrentPrice { get; set; }
        public int SkillLevel { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual ICollection<Reagent> Reagents { get; set; }
        public virtual Tradeskill Tradeskill { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
