//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WoWEntities : DbContext
    {
        public WoWEntities()
            : base("name=WoWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Companion> Companions { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Realm> Realms { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Tradeskill> Tradeskills { get; set; }
        public virtual DbSet<Reagent> Reagents { get; set; }
    }
}
