ALTER TABLE [dbo].[Characters]
    ADD CONSTRAINT [PK_Characters] PRIMARY KEY CLUSTERED ([CharacterId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
