ALTER TABLE [dbo].[CharacterRecipes]
    ADD CONSTRAINT [PK_CharacterRecipes] PRIMARY KEY CLUSTERED ([CharacterId] ASC, [RecipeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

