ALTER TABLE [dbo].[Recipes]
    ADD CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED ([RecipeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

