ALTER TABLE [dbo].[Realms]
    ADD CONSTRAINT [PK_Realms] PRIMARY KEY CLUSTERED ([RealmId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

