ALTER TABLE [dbo].[Tradeskills]
    ADD CONSTRAINT [PK_Tradeskills] PRIMARY KEY CLUSTERED ([TradeskillId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

